### ISSUE TITLE
Feature Request: Dynamically generate application "connection profile" with script 

### ISSUE THREAD

**Issue by gWOLF3** [APGGroeiFabriek/PIVT#10]
**What:**

Connection profile is commonly used in HF applications as a 'gateway' to interact with the network. 

See example profile defined here: 
https://hyperledger-fabric.readthedocs.io/en/release-1.4/developapps/connectionprofile.html#sample

Overview:
https://hyperledger-fabric.readthedocs.io/en/release-1.4/developapps/connectionprofile.html#connection-profile

**Why:**

Manually generating connection profiles is tedious and a hellish activity that should be automated but currently there is no good way. I would like to extend the funcitonality of PIVT to be able to generate a connection profile, similar to how it already does for networks. 

**How:**

This could probably be done using a basic template and some yaml filtering tools -> probably packaged as a script. This tool could be independent of any framework and simply accept as inputs a network definition for a chaincode and the default template. 

___

This is just a few initial thoughts, but this could be something really awesome to have. What are your thoughts on this/ any suggestions for implementation ?

**Comment by gWOLF3** [comment]
May be possible to create a dynamic gateway using Service Discovery CLI? 

https://hyperledger-fabric.readthedocs.io/en/release-1.4/discovery-overview.html#service-discovery

**Comment by gWOLF3** [comment]
Unsure if this is in scope.

I closed `application support feature` issue as out of scope. Since `connection-profile` is related to applications, I will say this is also out of scope. 

I will still implement and support this feature on my extension of this repo (fork chain-gang/PIVT)

**Closing FR...**

**Comment by rpocase** [comment]
Just ran into the same problem now that I'm ready to integrate my application. I'd argue service discovery would be extremely applicable to the repo and a toy application integration. Fabric is only useful with at least one application sitting on top driving the chain.

**Comment by gWOLF3** [comment]
I haven't implemented this yet - for now I'm just using the 'collect_host_aliases.sh' and updating the sample-app-gateway.yaml file with those values. Its not bad but the "right" way to do this would definitely be not needing to define a strict gateway configuration to begin with. As pods get restarted, this file need to be continually updated and its not a good practice. 

As for a sample app, you can find how I've implemented commercial paper. I tried to keep it very much within the same deployment paradigm as the rest of the repo. i still have a couple more things to do to make it dead simple, but this should provide for most user need of a 'toy' app like you said to test their network. I added a section to the docs 'launching an application'

**Comment by rpocase** [comment]
Interesting - hadn't thought to do that. As far as I can tell, this won't contain all the config I need for the network-config.yaml, though.

For my app, I'm going down the route of fully generating a network-config.yaml at upstart. My app pods shouldn't need to restart as I'll be consuming this as a secret.

**Comment by raftAtGit** [comment]
@rpocase  I will be happy to accept a PL for a simple toy application :)

in our project we dont use connection profiles or service discovery. just quickly checked the docs and looks like there is not much need actually. because of two reasons:

1. We and also this repo do no make distinction between endorser and committer peers for the sake of simplicity. Each peer is both endorser and committer. But if you need that distinction please see [FAQ](
https://github.com/APGGroeiFabriek/PIVT/blob/master/FAQ.md#how-can-i-distinguish-between-endorser-and-committer-peers-when-running-a-network-with-multiple-peers-per-organization)
2. Service discovery is provided by Kubernetes. It knows better than any other thing which Pod is down and routes traffic accordingly. Assuming you are using load balancing services, like `Peer-Org`, `Orderer-Org` or `Orderer-LB`. 
Please note, as of now, this is not possible with Raft orderer because of TLS. Raft without TLS is [implemented](https://jira.hyperledger.org/browse/FAB-15648) and will be released soon by Fabric guys.
With slight modifications to this repo, you can also setup load balancing among endorser and committer peers.

@gWOLF3 passing `hostAliases` to application pods is only required when TLS is enabled. Otherwise you can always use internal service names of peers and orderers, or better use load balancing services.
