### ISSUE TITLE
When we looking to implement  Fabric CA to generate certificates and private keys than using cryptogen

### ISSUE THREAD

**Issue by abhisamant7** [APGGroeiFabriek/PIVT#79]
Hi All,

  I think this project is best one to implement HLF in production with k8s however I noticed that this project used “Cryptogen” utility to generate certificates and Private keys. This is not a recommended approach in production.
 @raftAtGit when we implement  Fabric-ca so this project will be used in production also   

Thanks & Regards,
Abhi

**Comment by raftAtGit** [comment]
I do not agree that `cryptogen` is not suitable for production. it depends on your requirements. there is no **real** issue with cryptogen, only cosmetic details.

check the [FAQ](https://github.com/APGGroeiFabriek/PIVT/blob/master/FAQ.md#im-not-using-cryptogen-tool-but-we-are-creating-our-own-certificates-can-i-still-use-these-charts) about using another tool instead of cryptogen.

There is also a long discussion in [Fabric mail list](https://lists.hyperledger.org/g/fabric/topic/alternative_of_cryptogen_for/40860288) which I also participated. 

people keep saying `cryptogen` is not suggested for production without suggesting any other convenient tool. 

maybe one good option is, as also mentioned in that threat, modifying cryptogen to fix cosmetic issues and adding more features.

**Comment by abhisamant7** [comment]
Hi Raft,

Thanks for sharing info.
